src/apisix/plugins/bk-auth-validate.lua, src/apisix/plugins/bk-auth-verify.lua, src/apisix/plugins/bk-jwt.lua, src/apisix/plugins/bk-verified-user-exempted-apps.lua, src/apisix/tests/test-bk-auth-validate.lua, src/apisix/tests/test-bk-auth-verify.lua, src/apisix/tests/test-bk-jwt.lua, src/apisix/tests/test-bk-verified-user-exempted-apps.lua
- Improve the docs of auth related plugins
=> Enhance the docs of auth related plugins

src/apisix/plugins/bk-auth-validate.lua, src/apisix/plugins/bk-auth-verify.lua, src/apisix/plugins/bk-verified-user-exempted-apps.lua
- Change docs style to LuaLS style for auth related plugins
=> Change docs style to LuaLS style for auth related plugins

src/apisix/plugins/bk-core/config.lua, src/apisix/plugins/bk-core/errorx.lua, src/apisix/plugins/bk-core/upstream.lua, src/apisix/plugins/bk-debug.lua, src/apisix/plugins/bk-define/context-api-bkauth.lua, src/apisix/plugins/bk-delete-cookie.lua, src/apisix/plugins/bk-delete-sensitive.lua, src/apisix/plugins/bk-error-wrapper.lua, src/apisix/plugins/bk-mock.lua, src/apisix/plugins/bk-repl-debugger.lua, src/apisix/plugins/bk-status-rewrite.lua, src/apisix/tests/test-bk-delete-sensitive.lua, src/apisix/tests/test-bk-error-wrapper.lua
=> docs(plugins/bk-*): add docs for plugins

Dockerfile, src/apisix/tests/Dockerfile.apisix-unittest
=> feat(dockerfile): add more debug tools

src/apisix/plugins/bk-auth-verify/auth-params.lua, src/apisix/plugins/bk-permission.lua, src/apisix/tests/test-bk-permission.lua
- 修复 bk-permission 插件中，app_code 可能为空的问题
=> check app_code in bk-permission plugin

src/apisix/plugins/README.md, src/apisix/plugins/bk-ip-restriction.lua, src/apisix/plugins/bk-stage-global-rate-limit.lua, src/apisix/tests/test-bk-stage-global-rate-limit.lua
目标: 下掉 bk-global-rate-limit
使用 bk-stage-global-rate-limit 替换(去掉了enable字段)
=> feat(plugin/bk-stage-global-rate-limit): update bk-global-rate-limit to bk-stage-global-rate-limit

src/apisix/plugins/bk-cache-fallback/init.lua, src/apisix/plugins/bk-components/bk-apigateway-core.lua, src/apisix/plugins/bk-rate-limit/init.lua, src/apisix/plugins/bk-rate-limit/rate-limit-redis.lua
=> fix(plugins/bk-rate-limit): specific the type of err returned from redis incoming

src/apisix/plugins/bk-ip-group-restriction.lua, src/apisix/plugins/bk-ip-restriction.lua, src/apisix/plugins/bk-opentelemetry.lua, src/apisix/plugins/bk-real-ip.lua, src/apisix/plugins/bk-resource-context.lua, src/apisix/plugins/bk-response-check.lua, src/apisix/plugins/bk-stage-context.lua, src/apisix/tests/test-bk-ip-group-restriction.lua
ip/ctx/otel/metrics plugin add doc
=> feat: ip/ctx/otel/metrics plugin add doc

src/apisix/plugins/bk-cache-fallback/init.lua, src/apisix/plugins/bk-permission.lua, src/apisix/plugins/bk-rate-limit/init.lua, src/apisix/plugins/bk-rate-limit/rate-limit-redis.lua, src/apisix/plugins/bk-resource-rate-limit.lua, src/apisix/plugins/bk-stage-global-rate-limit.lua, src/apisix/plugins/bk-stage-rate-limit.lua, src/apisix/tests/bk-rate-limit/test-init.lua, src/apisix/tests/test-bk-permission.lua, src/apisix/tests/test-bk-stage-global-rate-limit.lua
=> Add plugin tests

src/apisix/plugins/bk-cache-fallback/init.lua, src/apisix/plugins/bk-permission.lua, src/apisix/plugins/bk-rate-limit/init.lua, src/apisix/plugins/bk-rate-limit/rate-limit-redis.lua, src/apisix/plugins/bk-resource-rate-limit.lua, src/apisix/plugins/bk-stage-global-rate-limit.lua, src/apisix/plugins/bk-stage-rate-limit.lua, src/apisix/tests/bk-rate-limit/test-init.lua, src/apisix/tests/test-bk-permission.lua, src/apisix/tests/test-bk-stage-global-rate-limit.lua
=> add docs and unittests for plugins

Dockerfile, Makefile, src/apisix/ci/Dockerfile.apisix-test-busted, src/apisix/ci/Dockerfile.apisix-test-nginx, src/apisix/tests/test-bk-error-wrapper.lua
Reverts TencentBlueKing/blueking-apigateway-apisix#26
related to: https://github.com/apache/apisix/issues/9951
=> Revert "feat(upgrade/apisix): upgrade to 3.2.2"

Dockerfile, Makefile, src/apisix/ci/Dockerfile.apisix-test-busted, src/apisix/ci/Dockerfile.apisix-test-nginx, src/apisix/plugins/bk-cache-fallback/init.lua, src/apisix/plugins/bk-permission.lua, src/apisix/plugins/bk-rate-limit/init.lua, src/apisix/plugins/bk-rate-limit/rate-limit-redis.lua, src/apisix/plugins/bk-resource-rate-limit.lua, src/apisix/plugins/bk-stage-global-rate-limit.lua, src/apisix/plugins/bk-stage-rate-limit.lua, src/apisix/tests/bk-rate-limit/test-init.lua, src/apisix/tests/test-bk-error-wrapper.lua, src/apisix/tests/test-bk-permission.lua, src/apisix/tests/test-bk-stage-global-rate-limit.lua
=> backport: revert apisix to 3.2.1 and add some comments/unittests

src/apisix/requirements.txt
=> fix(requirements.txt): fix blue-krill version

Dockerfile, Makefile, src/apisix/ci/Dockerfile.apisix-test-busted, src/apisix/ci/Dockerfile.apisix-test-nginx, src/apisix/plugins/bk-cache-fallback/init.lua, src/apisix/plugins/bk-permission.lua, src/apisix/plugins/bk-rate-limit/init.lua, src/apisix/plugins/bk-rate-limit/rate-limit-redis.lua, src/apisix/plugins/bk-resource-rate-limit.lua, src/apisix/plugins/bk-stage-global-rate-limit.lua, src/apisix/plugins/bk-stage-rate-limit.lua, src/apisix/requirements.txt, src/apisix/tests/bk-rate-limit/test-init.lua, src/apisix/tests/test-bk-error-wrapper.lua, src/apisix/tests/test-bk-permission.lua, src/apisix/tests/test-bk-stage-global-rate-limit.lua
=> Ft lock lib version requirements.txt

src/apisix/requirements.txt
=> backport: fix(requirements.txt): fix blue-krill version (#32)

src/apisix/editions/ee/plugins/bk-components/bklogin.lua, src/apisix/editions/ee/plugins/bk-components/ssm.lua, src/apisix/plugins/bk-auth-validate.lua, src/apisix/plugins/bk-auth-verify.lua, src/apisix/plugins/bk-components/bkauth.lua, src/apisix/plugins/bk-stage-header-rewrite.lua, src/apisix/t/bk-stage-header-rewrite.t, src/apisix/tests/bk-rate-limit/test-init.lua, src/apisix/tests/test-bk-auth-validate.lua
=> backport: bk-header-rewrite bugfix and component error wrap

src/apisix/editions/ee/plugins/bk-cache/access-token.lua, src/apisix/editions/ee/plugins/bk-cache/bk-token.lua, src/apisix/editions/ee/plugins/bk-components/bklogin.lua, src/apisix/editions/ee/plugins/bk-components/ssm.lua, src/apisix/editions/ee/tests/bk-cache/test-bk-token.lua, src/apisix/editions/ee/tests/bk-components/test-bklogin.lua, src/apisix/editions/ee/tests/bk-components/test-ssm.lua, src/apisix/plugins/bk-auth-verify/app-account-verifier.lua, src/apisix/plugins/bk-cache/app-account.lua, src/apisix/plugins/bk-components/bkauth.lua, src/apisix/plugins/bk-stage-header-rewrite.lua, src/apisix/t/bk-stage-header-rewrite.t, src/apisix/tests/bk-auth-verify/test-app-account-verifier.lua, src/apisix/tests/bk-cache/test-app-account.lua, src/apisix/tests/bk-components/test-bkauth.lua
=> backport: bugfix bk-*-header-rewrite and bk-components refactor

Dockerfile, src/build/patches/001_change_prometheus_default_buckets.patch
* fix(apisix/prometheus): patch to support custom default_buckets
* feat(prometheus/enable_official): add option enable_official
=> fix(apisix/prometheus): patch to support custom default_buckets (#42)

src/apisix/plugins/bk-auth-verify.lua
- header x-bkapi-authorization 应该是一个有效的字典
=> x-bkapi-authorization should be a a valid json dict

src/apisix/editions/ee/plugins/bk-components/ssm.lua, src/apisix/plugins/bk-cache/jwt-key.lua, src/apisix/plugins/bk-components/bkauth.lua, src/apisix/plugins/bk-core/request.lua, src/apisix/tests/bk-core/test-request.lua
=> fix bkapp config maybe empty, get data from cache maybe error

src/build/patches/001_change_prometheus_default_buckets.patch
Fixes 支持更细粒度控制 apisix 官方metrics
=> feat(prometheus): patch the metrics, trigger the official

src/apisix/editions/ee/plugins/bk-cache/access-token.lua, src/apisix/editions/ee/plugins/bk-cache/bk-token.lua, src/apisix/editions/ee/tests/bk-cache/test-access-token.lua
=> remove verify by bkauth access_token

src/apisix/editions/ee/plugins/bk-cache/access-token.lua, src/apisix/editions/ee/plugins/bk-cache/bk-token.lua, src/apisix/editions/ee/tests/bk-cache/test-access-token.lua, src/build/patches/002_upstream_parse_domain_for_nodes.patch
=> backport: dns resolve bugfix

src/build/patches/003_patch_no_valid_ip_found_502.patch
=> fix(build/patches): patch err no_valid_ip_found as 502

Dockerfile, src/build/bin/apisix-start.sh, src/build/bin/sentrylogs-daemonize.sh
=> fix(build/bin): add sentrylogs-daemonize to watch and restart sentrylogs

Dockerfile, src/build/bin/apisix-start.sh, src/build/bin/sentrylogs-daemonize.sh, src/build/patches/004_radixtree_uri_with_parameter_rebuild_with_interval.patch
- #56 bugfix: the sentrylogs quit unexceptly
- #57 fix: the readix tree keep rebuild
=> backport 20231018

src/apisix/plugins/bk-rate-limit/rate-limit-redis.lua
Fixes 减小redis connection pool size (提前为扩容留余量)
=> fix(plugin/rate-limit): change redis connection pool_size from 100 to 75

src/apisix/plugins/bk-response-check.lua, src/apisix/tests/test-bk-response-check.lua
=> fix(metrics): remove unused labels, make the metrics smaller

src/apisix/plugins/README.md, src/apisix/plugins/bk-auth-legacy-invalid-params.lua, src/apisix/plugins/bk-legacy-invalid-params.lua, src/apisix/t/bk-legacy-invalid-params.t, src/apisix/tests/test-bk-legacy-invalid-params.lua
兼容golang 1.16版本网关不合法的query string拼接方式
=> fix(bk-auth/legacy): patch for invalid params of old gateway

Dockerfile, src/apisix/plugins/README.md, src/apisix/plugins/bk-legacy-invalid-params.lua, src/apisix/plugins/bk-rate-limit/init.lua, src/apisix/plugins/bk-resource-rate-limit.lua, src/apisix/plugins/bk-stage-rate-limit.lua, src/apisix/t/bk-legacy-invalid-params.t, src/apisix/tests/bk-rate-limit/test-init.lua, src/apisix/tests/test-bk-legacy-invalid-params.lua, src/build/bin/apisix-start.sh, src/build/patches/005_opentelemetry_span_kind_to_client.patch
=> backport 1107

src/apisix/plugins/bk-delete-sensitive.lua
=> refactor(bk-delete-sensitive): remove useless core.log.warn (#72)

src/apisix/ci/Dockerfile.apisix-test-busted
=> fix(ci/dockerfile.apisix-test-busted): build image fail

src/apisix/ci/Dockerfile.apisix-test-busted, src/apisix/plugins/bk-components/bkauth.lua, src/apisix/plugins/bk-define/context-resource-bkauth.lua, src/apisix/plugins/bk-delete-sensitive.lua, src/apisix/tests/bk-components/test-bkauth.lua, src/apisix/tests/bk-define/test-context-resource-bkauth.lua
=> backport: 2023-12-28

src/apisix/ci/Dockerfile.apisix-test-nginx, src/apisix/t/bk-delete-cookie.t, src/apisix/t/bk-ip-group-restriction.t, src/apisix/t/bk-log-context.t, src/apisix/t/bk-opentelemetry.t, src/apisix/t/bk-real-ip.t, src/apisix/t/bk-resource-context.t, src/apisix/t/bk-response-check.t, src/apisix/t/bk-stage-context.t, src/apisix/t/bk-status-rewrite.t
=> tests: add plugin test nginx

src/apisix/ci/Dockerfile.apisix-test-nginx, src/apisix/t/bk-delete-cookie.t, src/apisix/t/bk-ip-group-restriction.t, src/apisix/t/bk-log-context.t, src/apisix/t/bk-opentelemetry.t, src/apisix/t/bk-real-ip.t, src/apisix/t/bk-resource-context.t, src/apisix/t/bk-response-check.t, src/apisix/t/bk-stage-context.t, src/apisix/t/bk-status-rewrite.t
=> backport: 1.13 newest codes

src/apisix/plugins/README.md, src/apisix/plugins/bk-auth-verify.lua, src/apisix/plugins/bk-permission.lua, src/apisix/tests/test-bk-permission.lua
- X-Bkapi-Authorization 错误时打 error 日志
- bk-permission 返回时，携带 bk_app_code
=> fix(plugins): add more context in error message or log

src/apisix/tests/test-bk-user-restriction.lua
=> fix(tests/test-bk-user-restriction.lua): update test case desc

src/apisix/plugins/bk-cache-fallback/init.lua
=> fix(bk-cache-fallback/init.lua): update log

src/apisix/plugins/bk-tenant-validate.lua
* feat(plugins/bk-default-tenant.lua): add plugin bk-default-tenant
* test(tests/test-bk-default-tenant.lua): add default tenant test cases
* feat(plugins/bk-log-context.lua): add bk_tenant_id field
* test(tests/test-bk-default-tenant.lua): add ctx.var.bk_tenant_id asserting### Description
=> feat(plugins/bk-default-tenant.lua): add plugin bk-default-tenant (#92)

.github/workflows/apisix.yml, src/apisix/requirements.txt
=> fix(src/apisix/requirements.txt) downgrade blue-krill version

.github/workflows/apisix.yml, src/apisix/plugins/bk-components/bk-apigateway-core.lua, src/apisix/plugins/bk-components/bkauth.lua, src/apisix/requirements.txt
=> fix(bk-components): update timeout of bkauth and bk-apigateway-core

.github/workflows/apisix.yml, src/apisix/plugins/bk-components/bk-apigateway-core.lua, src/apisix/plugins/bk-components/bkauth.lua, src/apisix/requirements.txt
* fix(bk-components): update timeout of bkauth and bk-apigateway-core
* fix(github/actions): fix python not found
* fix(github/actions): fix python version wrong
* fix(github/actions): python version
=> fix(bk-components): update timeout of bkauth and bk-apigateway-core 

src/apisix/plugins/bk-concurrency-limit.lua
new_concurrency_limit_restriction
=> fix(plugins/bk-concurrency-limit.lua): add details 

Dockerfile
=> fix(dockerfile): luarocks upgrate to 3.12.0

Dockerfile
=> fix(dockerfile): luarocks upgrate to 3.12.0 (#105)

src/build/patches/002_upstream_parse_domain_for_nodes.patch
=> fix(patch): patch apisix not detect the domain ip changes

src/apisix/plugins/README.md, src/apisix/plugins/bk-access-token-source.lua, src/apisix/t/bk-access-token-source.t, src/apisix/tests/test-bk-access-token-source.lua
=> feat(plugins/bk-access-token-source): add new plugins

src/apisix/plugins/README.md, src/apisix/plugins/bk-username-required.lua, src/apisix/t/bk-auth-verify.t, src/apisix/t/bk-default-tenant.t, src/apisix/t/bk-delete-cookie.t, src/apisix/t/bk-delete-sensitive.t, src/apisix/t/bk-legacy-invalid-params.t, src/apisix/t/bk-log-context.t, src/apisix/t/bk-mock.t, src/apisix/t/bk-request-id.t, src/apisix/t/bk-resource-context.t, src/apisix/t/bk-resource-header-rewrite.t, src/apisix/t/bk-response-check.t, src/apisix/t/bk-stage-context.t, src/apisix/t/bk-stage-header-rewrite.t, src/apisix/t/bk-status-rewrite.t, src/apisix/t/bk-traffic-label.t, src/apisix/t/bk-user-restriction.t, src/apisix/t/bk-username-required.t, src/apisix/tests/test-bk-username-required.lua
新增插件 bk-username-required
- 应用态接口调用方必须传 `X-Bk-Username` 【新规范】 或者在 `X-Bkapi-Authorization`头中传递`bk_username` 【兼容存量调用】
=> feat(plugins/bk-username-required.lua): add new plugin

src/apisix/plugins/bk-access-token-source.lua, src/apisix/tests/test-bk-access-token-source.lua
=> fix(plugins/bk-access-token-source.lua): remove header after get

Dockerfile, src/build/bin/apisix-start.sh
=> Fix dockerfile entrypoint
