TencentBlueKing/blueking-apigateway-apisix

src/apisix/plugins/bk-response-check.lua, src/apisix/tests/test-bk-response-check.lua
将 path 换成 matched_uri, 减少metrics数量(统计视图中只用到了route_id/route_name, 不会用到path)
- 原来 `path="/api/httpbin/prod/status/200/"`  (500/404等等)
- 改为 `matched_uri="/api/httpbin/prod/status/:codes/?"`
=> feat(plugin/bk-response-check): change prometheus label path to matched_uri, decrease the metrics

src/apisix/plugins/bk-components/bk-apigateway-core.lua
解决线上偶发timeout问题
后续 `apigateway-core-api` 接入 APM 后重点优化掉这类问题
=> feat(bk-components/bk-apigateway-core): change timeout to 5s

src/apisix/plugins/bk-stage-header-rewrite.lua, src/apisix/t/bk-stage-header-rewrite.t
=> bugfix: header rewrite empty

Dockerfile, src/build/patches/001_change_prometheus_default_buckets.patch
- patch 到 3.2.1 以支持自定义设置 `default_buckets`
- 增加`enable_official` 以便在某些环境关闭官方metrics
相关pr: https://github.com/apache/apisix/pull/9673/files
=> fix(apisix/prometheus): patch to support custom default_buckets

src/build/patches/002_upstream_parse_domain_for_nodes.patch
修复: dns 偶发解析失败导致apisix worker dns解析持续失败
https://github.com/apache/apisix/issues/10093#issuecomment-1738381865
=> fix(build/patches): add patch for parse_domain_for_nodes in apisix/utils/upstream.lua

src/apisix/editions/ee/plugins/bk-cache/access-token.lua, src/apisix/editions/ee/plugins/bk-cache/bk-token.lua, src/apisix/editions/ee/tests/bk-cache/test-access-token.lua, src/build/patches/002_upstream_parse_domain_for_nodes.patch, src/build/patches/003_patch_no_valid_ip_found_502.patch
=> backport: fix no valid ip found 502

src/build/patches/004_radixtree_uri_with_parameter_rebuild_with_interval.patch
当前问题: 如果`/routes`一直有更新并且一直有请求进来, 每个worker会一直重建radixtree cache
修复:
1. 实时判断重建改成周期判断重建
2. 增加随机时间段, 避免所有worker在同一个时间执行rebuild
=> feat(build/patches): patch radixtree_uri_with_parameter rebuild with interval

src/apisix/plugins/bk-response-check.lua, src/apisix/tests/test-bk-response-check.lua, src/build/patches/004_radixtree_uri_with_parameter_rebuild_with_interval.patch
Fixes 
- fix redis pool_size to a smaller value #60 
- fix `/metrics` to large, remove unused labels #59
=> backport: bugfix

src/apisix/plugins/bk-rate-limit/init.lua, src/apisix/plugins/bk-resource-rate-limit.lua, src/apisix/plugins/bk-stage-rate-limit.lua, src/apisix/tests/bk-rate-limit/test-init.lua
- 修复: 当前更新频率限制阈值需要等待原先的限制从redis中失效(ttl=period)
=> fix(bk-rate-limit): update the key to use new limits if the config changed

Dockerfile, src/build/bin/apisix-start.sh
Fixes apisix-start.sh 中进程启动顺序, apisix退出时脚本必须随之退出
=> fix(bin/apisix-start.sh): change the order of apisix start command

src/apisix/plugins/bk-auth-verify.lua, src/apisix/plugins/bk-define/context-api-bkauth.lua, src/apisix/plugins/bk-delete-sensitive.lua, src/apisix/plugins/bk-stage-context.lua, src/apisix/t/README.md, src/apisix/t/bk-auth-validate.t, src/apisix/t/bk-auth-verify.t, src/apisix/t/bk-delete-sensitive.t, src/apisix/t/bk-stage-context.t, src/apisix/tests/bk-define/test-context-api-bkauth.lua, src/apisix/tests/test-bk-auth-verify.lua, src/apisix/tests/test-bk-delete-sensitive.lua, src/apisix/tests/test-bk-stage-context.lua, src/apisix/typing.lua
=> 允许不从请求参数获取认证参数

src/apisix/plugins/bk-auth-verify/app-account-verifier.lua, src/apisix/tests/bk-auth-verify/test-app-account-verifier.lua, src/build/patches/006_use_encoded_uri_for_radixtree_match.patch
- 调用bkauth校验app_code/app_secret前, 提前 check 长度
- 修复 uri 参数中使用中文导致 404 问题
=> fix(bk-auth-verify): add app_code/app_secret length check

Dockerfile, src/apisix/plugins/README.md, src/apisix/plugins/bk-auth-verify.lua, src/apisix/plugins/bk-auth-verify/app-account-verifier.lua, src/apisix/plugins/bk-define/context-api-bkauth.lua, src/apisix/plugins/bk-delete-sensitive.lua, src/apisix/plugins/bk-legacy-invalid-params.lua, src/apisix/plugins/bk-rate-limit/init.lua, src/apisix/plugins/bk-resource-rate-limit.lua, src/apisix/plugins/bk-stage-context.lua, src/apisix/plugins/bk-stage-rate-limit.lua, src/apisix/t/README.md, src/apisix/t/bk-auth-validate.t, src/apisix/t/bk-auth-verify.t, src/apisix/t/bk-delete-sensitive.t, src/apisix/t/bk-legacy-invalid-params.t, src/apisix/t/bk-stage-context.t, src/apisix/tests/bk-auth-verify/test-app-account-verifier.lua, src/apisix/tests/bk-define/test-context-api-bkauth.lua, src/apisix/tests/bk-rate-limit/test-init.lua, src/apisix/tests/test-bk-auth-verify.lua, src/apisix/tests/test-bk-delete-sensitive.lua, src/apisix/tests/test-bk-legacy-invalid-params.lua, src/apisix/tests/test-bk-stage-context.lua, src/apisix/typing.lua, src/build/bin/apisix-start.sh, src/build/patches/005_opentelemetry_span_kind_to_client.patch, src/build/patches/006_use_encoded_uri_for_radixtree_match.patch
=> backport 20231130

src/apisix/plugins/bk-delete-sensitive.lua
- bk-delete-sensitive: 去掉log.warn auth params are present in both header and request
-
=> refactor(bk-delete-sensitive): remove useless core.log.warn

src/apisix/plugins/bk-components/bkauth.lua, src/apisix/tests/bk-components/test-bkauth.lua
fix bkauth request add request-id
=> fix: fix bkauth request add request-id

src/apisix/ci/Dockerfile.apisix-test-busted, src/apisix/ci/Dockerfile.apisix-test-nginx, src/apisix/editions/ee/plugins/bk-cache/bk-token.lua, src/apisix/plugins/bk-permission.lua, src/apisix/tests/test-bk-permission.lua
调整bk-permission cache 配置
1. 调大max_items
2. 降低某次请求core-api失败导致 30s 内请求都失败的影响
3. 兜底的 cache数据从 1 小时改成 12 小时，最小化避免core-api宕机导致的影响
=> feat(bk-permission): update cache settings

src/apisix/ci/Dockerfile.apisix-test-nginx, src/apisix/plugins/bk-mock.lua, src/apisix/t/bk-mock.t, src/apisix/tests/test-bk-mock.lua
bk-mock 设置header需要override 同名 key
=> fix(plugins/bk-mock): set_header should override same key

src/apisix/plugins/README.md, src/apisix/plugins/bk-core/errorx.lua, src/apisix/plugins/bk-user-restriction.lua, src/apisix/t/bk-user-restriction.t, src/apisix/tests/test-bk-user-restriction.lua
- add bk-user-restriction plugin
=> feat(plugins/bk-user-restriction): add new plugin

src/apisix/plugins/bk-components/bk-apigateway-core.lua, src/apisix/plugins/bk-components/bkauth.lua
bkauth和core-api的性能都非常好，一般10ms以内；但是由于网络问题/db 偶发查询慢，会导致偶发的 timeout；
1. 将默认超时时间减半
2. 增加一次重试, 解决偶发网络问题
=> fix(bk-components): add retry for timeout of core-api and bkauth

src/apisix/editions/ee/plugins/bk-cache/access-token.lua, src/apisix/editions/ee/plugins/bk-cache/bk-token.lua, src/apisix/editions/ee/plugins/bk-components/bklogin.lua, src/apisix/editions/ee/plugins/bk-components/ssm.lua, src/apisix/editions/ee/tests/bk-cache/test-access-token.lua, src/apisix/editions/ee/tests/bk-cache/test-bk-token.lua, src/apisix/editions/ee/tests/bk-components/test-bklogin.lua, src/apisix/editions/ee/tests/bk-components/test-ssm.lua, src/apisix/plugins/bk-cache/app-account.lua, src/apisix/plugins/bk-cache/jwt-key.lua, src/apisix/plugins/bk-components/bkauth.lua, src/apisix/plugins/bk-define/access-token.lua, src/apisix/tests/bk-cache/test-app-account.lua, src/apisix/tests/bk-components/test-bkauth.lua
> 目标：即使依赖的第三方服务挂了，也能持续运行一段时间，确保大部分访问过的请求还能继续访问，直到服务恢复
- 鉴于 jwt 不会改变（且查询不到 404 不会缓存）， 将 lrucache的 ttl 改成 24 小时（如果改变，需要reload）
=> feat(bk-cache/jwt-key.lua): ha refactor to make the dp robust

src/apisix/Makefile, src/apisix/ci/run-test-nginx.sh, src/apisix/plugins/README.md, src/apisix/plugins/bk-traffic-label.lua, src/apisix/t/bk-00.t, src/apisix/t/bk-traffic-label.t, src/apisix/tests/test-bk-traffic-label.lua
参考 [api7: traffic-labels](https://docs.api7.ai/hub/traffic-label/) 文档实现的插件
流量染色插件，支持 match 匹配规则 + actions 执行染色两部分配置
- match 支持参数/header 头/cookie/nginx 内置变量/apisix内置变量等
- actions 目前支持多组操作，且支持配置权重；当前只支持 `set_headers` 操作
```json
"traffic-label": {
"rules": [
{
"match": [
["uri", "==", "/headers"]
],
"actions": [
{
"set_headers": {
"X-Server-Id": 100
}
}
]
}
]
}
"traffic-label": {
"rules": [
{
"match": [
"OR",
["arg_version", "==", "v1"],
["arg_env", "==", "dev"]
],
"actions": [
{
"set_headers": {
"X-Server-Id": 100
}
}
]
}
]
}
"traffic-label": {
"rules": [
{
"match": [
["uri", "==", "/headers"]
],
"actions": [
{
"set_headers": {
"X-Server-Id": 100
},
"weight": 3
},
{
"set_headers": {
"X-API-Version": "v2"
},
"weight": 2
},
{
"weight": 5
}
]
}
]
}
"traffic-label": {
"rules": [
{
"match": [ …
```
=> feat(plugins/bk-traffic-label.lua): add new plugin

src/apisix/plugins/README.md, src/apisix/plugins/bk-default-tenant.lua, src/apisix/plugins/bk-log-context.lua, src/apisix/t/bk-default-tenant.t, src/apisix/tests/test-bk-default-tenant.lua, src/apisix/tests/test-bk-log-context.lua
多租户需求：
- 多租户代码，但是没有开启多租户，处于单租户模式，此时需要默认给所有流量注入 `X-Bk-Tenant-Id: default`
- 增加 ctx.var.bk_tenant_id， 默认从 header中获取， 并且 default tenant中将之设置为`default`
=> feat(plugins/bk-default-tenant.lua): add plugin bk-default-tenant

src/apisix/editions/ee/plugins/bk-components/bklogin.lua, src/apisix/editions/ee/tests/bk-components/test-bklogin.lua, src/apisix/plugins/bk-cache/user-tenant-info.lua, src/apisix/plugins/bk-components/bkauth.lua, src/apisix/plugins/bk-components/bkuser.lua, src/apisix/plugins/bk-components/utils.lua, src/apisix/plugins/bk-core/config.lua, src/apisix/tests/bk-cache/test-user-tenant-info.lua, src/apisix/tests/bk-components/test-bkauth.lua, src/apisix/tests/bk-components/test-bkuser.lua, src/apisix/tests/conf/config.yaml
- fix: bklogin wrong url and no need to check code in response json
- fix: user-tenant-info use component bkuser
- fix: bkauth app tenant info is in `bk_tenant` not `tenant`
=> feat(plugins/bk-default-tenant.lua): add plugin bk-default-tenant (#92)

src/apisix/ci/Dockerfile.apisix-test-busted, src/apisix/ci/Dockerfile.apisix-test-nginx, src/apisix/plugins/bk-auth-verify/inner-jwt-verifier.lua, src/apisix/tests/bk-auth-verify/test-inner-jwt-verifier.lua
inner-jwt 不强制要求 user.verified=true， 如果没有提供或者false，创建匿名用户，往后走； 如果接口开启用户认证才会报错
=> feat(inner-jwt-verifier.lua): make user verified of inner-jwt optional
